### ISSUE TITLE
Pwnagotchi not booting anymore

### ISSUE THREAD

**Issue by sylarr** [kellertk/pwnagotchi-plugin-pisugar2#5]
I activated I2C, modified config.toml, and downloaded pisugar2.py into the custom plugins folder, but now the Pi doesn't turn on (only the LED turns on, but it turns off after a few seconds). What am I doing wrong?

**Comment by kellertk** [comment]
Well, it doesn't sound like anything wrong, but since I don't have your Pi in front of me I can't tell. You're going to need to dig into the logs on your device and see what's going on. Or possibly plug in a display and watch it boot.

I don't have the time to support people using this code, sorry. If you have a problem with the code itself (with logs) to report, I can look. Good luck!
